### PR TITLE
Added progressCallback and stop the http download if thread stop requ…

### PR DESCRIPTION
**Pull request by sureshsathiah**
…ested.

Signed-off-by: Suresh Sathiah <Suresh_Sathiah@comcast.com>

### CODE REVIEW

**Review by mfiess — APPROVED** [review]

**Comment by mhughesacn** [comment]
Hi Suresh,
Please place the Comcast headers on the very top of the files instead.
Thanks

**Comment by sureshsathiah** [comment]
> Hi Suresh,
> Please place the Comcast headers on the very top of the files instead.
> Thanks

Hello mhughesacn,
I have already placed this header on all those three files. Is the Comcast headers different than the below?

/**Copyright 2021 Comcast Cable Communications Management, LLCLicensed under the Apache License, Version 2.0 (the "License");you may not use this file except in compliance with the License.You may obtain a copy of the License athttp://www.apache.org/licenses/LICENSE-2.0Unless required by applicable law or agreed to in writing, softwaredistributed under the License is distributed on an "AS IS" BASIS,WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.See the License for the specific language governing permissions andlimitations under the License.SPDX-License-Identifier: Apache-2.0*/

Thanks,
Suresh

**Comment by sureshsathiah** [comment]
> Hi Suresh,
> Please place the Comcast headers on the very top of the files instead.
> Thanks



> Hi Suresh,
> Sorry, I thought I was clear: please will you put the Comcast header at the very top of the file, and then the existing John Robinson header, like example I gave yesterday (with RDK). This is how we handle this. I will approve at one when you make the change.
> Thanks, Martin

Hello Martin,
Added that header on top of the files.
Could you please review that again.
Thanks,
Suresh

**Comment by mhughesacn** [comment]
Thanks Suresh!  Checks are passing now.

**Pull request merged**
